### ISSUE TITLE
Doesn't work on OS X

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patric-r/jvmtop#37] opened 2015-07-14 12:59 UTC
```
What steps will reproduce the problem?
1. Try and run with OS X
2. Does not work.  Says requires real JDK.

tools.jar is not packaged up as a separate jar in the OS X JDK.  You don't need 
to add it to the classpath like on Windows/Unix.  I wrote and tested the 
following fix:

if [ `uname` != 'Darwin' ] ; then
  if [ ! -f "$TOOLSJAR" ] ; then
    echo "$JAVA_HOME seems to be no JDK!" >&2
    exit 1
  fi
fi




```

Original issue reported on code.google.com by `hughes.m...@gmail.com` on 10 Sep 2013 at 11:51

**Comment by patric-r** [comment] 2015-10-19 13:41
Most probably, this issue is a duplicate of #64 which has already been fixed.
If this issue still occurs within the next jvmtop release (0.9.0), please feel free to reopen.

**Closed by patric-r** 2015-10-19 13:41 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
